version: '3'

services:
  ui-designer:
    container_name: cssartist
    image: cssartist:latest
    build:
      context: ./gameBoard
      dockerfile: Dockerfile
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
        DRABOARD_URL: 'https://tie-lukioplus.rd.tuni.fi/drawboard'
        LOCAL_TESTING_URL: 'https://tie-lukioplus.rd.tuni.fi'
    ports:
      - 54322:3000
    environment:
      TZ: Europe/Helsinki
      NODE_ENV: production
    restart: always
    networks:
      ui-designer-network:
    depends_on:
      - drawboard
      - backend

  drawboard:
    container_name: drawboard
    image: drawboard:latest
    build:
      context: ./drawBoard
      dockerfile: Dockerfile
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    ports:
      - 54320:3000
    environment:
      TZ: Europe/Helsinki
      NODE_ENV: production
    restart: always
    networks:
      ui-designer-network:

  backend:
    container_name: cssartist.backend
    image: cssartist-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    environment:
      TZ: Europe/Helsinki
      NODE_ENV: production
    restart: always
    volumes:
      - ./backend/db:/usr/src/app/db:z
    networks:
      ui-designer-network:

networks:
  ui-designer-network:
